import {PageAPI} from '@api';
import {PostAPI} from '@domain';

export const postPageMocked: PageAPI<PostAPI> = {
  meta: {
    total: 4,
    per_page: 20,
    current_page: 1,
    last_page: 1,
    first_page: 1,
    first_page_url: '/?page=1',
    last_page_url: '/?page=1',
    next_page_url: null,
    previous_page_url: null,
  },
  data: [
    {
      id: 1,
      text: 'Bom dia!',
      user_id: 1,
      image_url: 'https://fakeAPI.com/post1.jpg',
      is_fixed: false,
      is_activated: true,
      created_at: '2024-04-25T03:32:29.163+00:00',
      updated_at: '2024-04-25T03:32:29.170+00:00',
      user: {
        id: 1,
        first_name: 'Maria',
        last_name: 'Julia',
        username: 'mariajulia',
        email: 'mariajulia@coffstack.com',
        profile_url: 'https://fakeAPI.com/1-maria.png',
        is_online: false,
        full_name: 'Maria Julia',
        meta: {
          following_count: '1',
          followers_count: '0',
        },
      },
      reactions: [],
      status: 'published',
      meta: {
        like_count: '6',
        favorite_count: '3',
        comments_count: '26',
      },
    },
    {
      id: 12,
      text: 'Chove chuva, chove sem parar ☔️',
      user_id: 1,
      image_url: 'https://fakeAPI.com/post12.jpg',
      is_fixed: false,
      is_activated: true,
      created_at: '2024-04-24T02:32:29.165+00:00',
      updated_at: '2024-04-25T03:32:29.203+00:00',
      user: {
        id: 1,
        first_name: 'Maria',
        last_name: 'Julia',
        username: 'mariajulia',
        email: 'mariajulia@coffstack.com',
        profile_url: 'https://fakeAPI.com/1-maria.png',
        is_online: false,
        full_name: 'Maria Julia',
        meta: {
          following_count: '1',
          followers_count: '0',
        },
      },
      reactions: [
        {
          emoji_type: 'like',
          post_id: 12,
        },
      ],
      status: 'published',
      meta: {
        like_count: '6',
        favorite_count: '2',
        comments_count: '1',
      },
    },
    {
      id: 17,
      text: 'home office be like: 🤓',
      user_id: 1,
      image_url: 'https://fakeAPI.com/post17.jpg',
      is_fixed: false,
      is_activated: true,
      created_at: '2024-04-23T03:20:29.165+00:00',
      updated_at: '2024-04-25T03:32:29.210+00:00',
      user: {
        id: 1,
        first_name: 'Maria',
        last_name: 'Julia',
        username: 'mariajulia',
        email: 'mariajulia@coffstack.com',
        profile_url: 'https://fakeAPI.com/1-maria.png',
        is_online: false,
        full_name: 'Maria Julia',
        meta: {
          following_count: '1',
          followers_count: '0',
        },
      },
      reactions: [],
      status: 'published',
      meta: {
        like_count: '5',
        favorite_count: '2',
        comments_count: '5',
      },
    },
    {
      id: 21,
      text: 'No coffee no code ☕️',
      user_id: 1,
      image_url: 'https://fakeAPI.com/post21.jpg',
      is_fixed: false,
      is_activated: true,
      created_at: '2024-04-22T02:32:29.165+00:00',
      updated_at: '2024-04-25T03:32:29.216+00:00',
      user: {
        id: 1,
        first_name: 'Maria',
        last_name: 'Julia',
        username: 'mariajulia',
        email: 'mariajulia@coffstack.com',
        profile_url: 'https://fakeAPI.com/1-maria.png',
        is_online: false,
        full_name: 'Maria Julia',
        meta: {
          following_count: '1',
          followers_count: '0',
        },
      },
      reactions: [
        {
          emoji_type: 'like',
          post_id: 21,
        },
      ],
      status: 'published',
      meta: {
        like_count: '7',
        favorite_count: '1',
        comments_count: '2',
      },
    },
  ],
};
