version: 2.1

jobs:
  pull-request-checks:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout

      - run:
          name: Install Packages
          command: yarn install

      - run:
          name: Run Lint
          command: yarn lint

      - run:
          name: Run TypeScript compiler
          command: yarn tsc --noEmit

      - run:
          name: Run test
          command: yarn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - pull-request-checks:
          filters:
            branches:
              only:
                - main
                - develop
