# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
skip_docs

platform :android do


  desc "Build AAB file and upload it to Google Play"
  lane :build_and_upload_internal do
    gradle(
      task: 'bundle',
       build_type:'release' 
    )

    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true
    )
    
  end

  desc "Upload to Google Play"
  lane :upload_internal do
    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      aab: 'app/build/outputs/bundle/release/app-release.aab'
    )
    
  end

end
