name: Create Bump PR
on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        ref: ${{env.BUMP_PR_BRANCH}}

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Packages
        run: yarn install

      - name: Make bump-version.sh  executable
        run: chmod +x bump-version.sh

      - name: Bum version
        run: ./bump-version.sh $GITHUB_REF_NAME

      - name: Git checkout
        run: git checkout -b "version/${{env.BUMP_PR_BRANCH}}"

      - name: create pull request
        run: gh pr create -B ${{env.BUMP_PR_BRANCH}} -H version/${{env.BUMP_PR_BRANCH}} --title "Bump version to ${GITHUB_REF_NAME}" --body "Created by Github action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
